fileFormatVersion: 2
guid: 74f140c827788b64ebde10a2197d3c0b
DefaultImporter:
  externalObjects: {}
  userData: 
  assetBundleName: 
  assetBundleVariant: 
AssetOrigin:
  serializedVersion: 1
  productId: 207815
  packageName: 'FishNet: Networking Evolved'
  packageVersion: 4.5.8R
  assetPath: Assets/FishNet/Plugins/Edgegap/Editor/Dockerfile
  uploadId: 726025
